### ISSUE TITLE
Not working in Zotero 7.0.7

### ISSUE THREAD

**Issue by DaudHamidi** [Dominic-DallOsto/zotero-reading-list#61] opened 2024-10-05 04:39 UTC
I updated Zotero to version 7.0.7 and realized that the plugin, although installed and enabled, is not appearing in the context menu when I right-click. I don't have any issues with other plugins.

**Comment by Yardie83** [comment] 2024-10-05 11:11
Same with Better BibTex. When disabled, the plugin works. Otherwise it doesn't.

**Comment by Dominic-DallOsto** [comment] 2024-10-08 18:11
This is a duplicate of #58

Can you let me know in that issue if v1.5.2 fixes it for you?

**Closed by Dominic-DallOsto** 2024-10-08 18:11 UTC
