### ISSUE TITLE
Why the icon of read status turn black and white?

### ISSUE THREAD

**Issue by UCPRER** [Dominic-DallOsto/zotero-reading-list#63] opened 2024-10-13 13:01 UTC
![image](https://github.com/user-attachments/assets/760abaa6-e369-43c0-883a-a4b4b037c6ae)

**Comment by Dominic-DallOsto** [comment] 2024-10-13 22:18
This seems like a duplicate of #37

Can you follow the instructions in that issue, basically to check if the emojis show up properly in any other text boxes in Zotero. If this isn't the case, this is a problem with Zotero, not with this plugin.

But which versions of Zotero and of this plugin are you using? And which operating system?

**Closed** 2024-11-09 10:45 UTC
Labels: bug, duplicate, more info needed
